#!/usr/bin/env python3
"""
Second enrichment pass: replace template-based CLIP documents with
vivid visual scene descriptions generated by Claude Haiku.

Run from project root with venv activated:
    python scripts/enrich_haiku.py

Requires ANTHROPIC_API_KEY in .env and a populated songs table.
"""

import os
import sys
import time
import logging
from pathlib import Path

from dotenv import load_dotenv
import anthropic
import numpy as np
from sqlalchemy import text

sys.path.insert(0, str(Path(__file__).parent.parent))

from backend.core.clip_encoder import CLIPEncoder
from backend.db.database import SessionLocal

load_dotenv()
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

BATCH_SIZE = 50

SYSTEM_PROMPT = (
    "You are a visual scene describer for a music-to-image matching system. "
    "Given a song title, artist, and genre, write a 1-2 sentence visual scene description "
    "that captures the mood, setting, and aesthetic this song evokes. "
    "Write as if describing a photograph or movie still — concrete imagery, colors, lighting, "
    "textures, atmosphere. No abstract emotions, no music terminology, no lyrics. "
    "Reply with ONLY the description, nothing else."
)


def generate_descriptions(client: anthropic.Anthropic, songs: list[dict]) -> list[str]:
    """Call Haiku for each song and return visual descriptions."""
    descriptions: list[str] = []

    for i, song in enumerate(songs):
        prompt = f"Song: \"{song['title']}\" by {song['artist']} (genre: {song['genre']})"
        try:
            resp = client.messages.create(
                model="claude-haiku-4-5-20251001",
                max_tokens=150,
                system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": prompt}],
            )
            desc = resp.content[0].text.strip()
            descriptions.append(desc)
        except Exception as exc:
            log.warning(f"Haiku failed for {song['title']}: {exc}")
            descriptions.append(
                f"{song['title']} by {song['artist']}. {song['genre']} music."
            )

        if (i + 1) % 100 == 0:
            log.info(f"  {i + 1}/{len(songs)} descriptions generated")

    return descriptions


def main() -> None:
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        log.error("ANTHROPIC_API_KEY not set in .env")
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)

    db = SessionLocal()
    try:
        rows = db.execute(
            text("SELECT id, title, artist, genre FROM songs ORDER BY id")
        ).fetchall()
        songs = [{"id": r[0], "title": r[1], "artist": r[2], "genre": r[3]} for r in rows]
    finally:
        db.close()

    log.info(f"Generating Haiku descriptions for {len(songs)} songs...")
    descriptions = generate_descriptions(client, songs)

    log.info("Sample descriptions:")
    for s, d in zip(songs[:5], descriptions[:5]):
        log.info(f"  {s['title']} — {s['artist']}")
        log.info(f"    → {d}")

    log.info(f"Encoding {len(descriptions)} descriptions with CLIP...")
    encoder = CLIPEncoder()
    embeddings: list[np.ndarray] = []
    for i, desc in enumerate(descriptions):
        embeddings.append(encoder.encode_text(desc))
        if (i + 1) % 200 == 0:
            log.info(f"  {i + 1}/{len(descriptions)} encoded")

    log.info("Updating database...")
    db = SessionLocal()
    try:
        for i in range(0, len(songs), BATCH_SIZE):
            batch = songs[i : i + BATCH_SIZE]
            batch_desc = descriptions[i : i + BATCH_SIZE]
            batch_emb = embeddings[i : i + BATCH_SIZE]

            for song, desc, emb in zip(batch, batch_desc, batch_emb):
                db.execute(
                    text(
                        "UPDATE songs SET document = :doc, embedding = :emb WHERE id = :id"
                    ),
                    {"doc": desc, "emb": str(emb.tolist()), "id": song["id"]},
                )
            db.commit()
            log.info(f"  {min(i + BATCH_SIZE, len(songs))}/{len(songs)} rows updated")

        log.info("Done — all documents and embeddings updated.")
    finally:
        db.close()


if __name__ == "__main__":
    main()
